main/urls.py
from django.urls import path
from .import views


app_name = 'main'

urlpatterns = [
	path('',views.index, name='homePage' ),
	path('contact/',views.contact, name='contactPage' ),
	path('blog/',views.blog, name='blogPage' ),
	path('blog/<str:post_slug>',views.blog_detail, name='blogDetailPage' ),

	path('search_results/', views.search, name='search'),
]

nature/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

class Course(models.Model):
	name = models.CharField('Kurs nomi', max_length=150)
	time = models.CharField('Kurs vaqti', max_length=50)
	image = models.ImageField(upload_to='course_images/')
	price = models.PositiveIntegerField('Narxi', default=0)
	student_age = models.CharField('Talabalar yosh chegarasi', max_length=50)
	size = models.CharField('Talabalar soni', max_length=50)
	teacher = models.CharField('Ustoz', max_length=150)
	duration = models.CharField('Davom etish vaqti', max_length=50, blank=True)

	class  Meta:
		verbose_name = 'Kurs'
		verbose_name_plural = 'Kurslar'

	def __str__(self):
		return "Kurs nomi {}".format(self.name)

class Contact(models.Model):
	name = models.CharField('Ismi', max_length=50)
	email = models.EmailField('Email', max_length=250)
	message = models.TextField('Xabar',)

	class  Meta:
		verbose_name = 'Aloqa'
		verbose_name_plural = 'Aloqalar'

	def __str__(self):
		return f"{self.name}"




class Categories(models.Model):
	name = models.CharField('Kategoriya nomi', max_length=70)
	slug = models.SlugField('*', max_length=50, unique=True, db_index=True)

	class Meta:
		verbose_name = 'Kategoriya'
		verbose_name_plural = 'Kategoriyalar'

	def __str__(self):
		return f"{self.name}"


class Tag(models.Model):
	name = models.CharField('Tag nomi', max_length=70)
	slug = models.SlugField('*', max_length=50, unique=True, db_index=True)

	class Meta:
		verbose_name = 'Tag'
		verbose_name_plural = 'Taglar'

	def __str__(self):
		return f"{self.name}"


class Post(models.Model):
	title = models.CharField('Maqola nomi', max_length=250)
	slug = models.SlugField('*',max_length=100, unique=True, db_index=True)
	image = models.ImageField('rasmi', upload_to='post_poster/')
	body = RichTextField()
	category = models.ForeignKey(Categories, on_delete=models.CASCADE, blank=True, null=True)
	tag = models.ForeignKey(Tag,on_delete=models.PROTECT, blank=True, null=True)
	author = models.CharField('Muallif', default='Admin',max_length=100, blank=True)
	published = models.DateTimeField("Qo'shilgan vaqti", auto_now_add=True)
	most_read = models.BooleanField(default=False)
	top = models.BooleanField(default=False)


	class Meta:
		verbose_name = 'Maqola'
		verbose_name_plural = 'Maqolalar'

	def get_absolute_url(self):
		return reverse('main:blogDetailPage', kwargs={'post_slug':self.slug})

	def __str__(self):
		return f"{self.title}"


class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
	name = models.CharField('Ismi', max_length=50)
	email = models.EmailField('Email', max_length=250)
	subject = models.CharField('Mavzudi', max_length=250)
	message = models.TextField('Xabar',)

	class  Meta:
		verbose_name = 'Muhokama'
		verbose_name_plural = 'Muhokamalar'

	def __str__(self):
		return f"{self.name}"

class Register(models.Model):
	CHOICES = (
		('Python','python'),
		('Javascript','javascript'),
		('C++','cpp'),
		('C#','csharp'),
		('Ruby','ruby'),
		('Flutter','flutter'),
		)
	name = models.CharField('Ism-Familya', max_length=50)
	email = models.EmailField()
	course = models.CharField('Tanlagan kursi', max_length=50, choices=CHOICES)
	message = models.TextField("Qo'shimcha xabar")

	class  Meta:
		verbose_name = "A'zo bo'lish"
		verbose_name_plural = "A'zo bo'lganlar"

	def __str__(self):
		return f"{self.name}"

main/forms.py
from django.forms import ModelForm,Textarea
from .models import Register


class JoinUsForm(ModelForm):
	""" Join us form to Register model """
	class Meta:
		model = Register
		fields = ('name','email','course','message')
		widgets = {
			'message': Textarea(attrs={'cols': 30, 'rows': 8}),
		}

main/views.py
from django.shortcuts import render
from .models import *
from django.contrib import messages
from .forms import 	JoinUsForm
#Search views
from django.db.models import Q
# Create your views here.
import telebot 


me = 668618297
TOKEN = '1133552059:AAH_ZpM-cZHniQoheUqmTNc-wHRE8Enow1c'
bot = telebot.TeleBot(TOKEN)


def search(request):
	query = request.GET.get('search')
	posts = Post.objects.filter(
		Q(title__icontains=query) & Q(body__icontains=query)
		)
	context = {
		'results':posts
	}
	return render(request, 'results.html', context)


def index(request):
	if request.method == 'POST':
		form = JoinUsForm(request.POST)
		if form.is_valid():
			form.save()
			print('*'*50)
		else:
			print('#'*50)
	else:
		form = JoinUsForm()
	posts = Post.objects.all().order_by('-published')[:3]
	most_read = Post.objects.filter(most_read=True)

	context = {
	'posts':posts, 
	'most_read':most_read,
	'form':form
	}

	return render(request, 'home.html',context)


def contact(request):
	if request.method == 'POST':
		n = request.POST['name']
		e = request.POST['email']
		m = request.POST['message']
		Contact.objects.create(name=n, email=e, message=m)
		bot.send_message(me, 'Saytdan xabar bor \n Ismi : {0}'.format(n))
		print('*'*50)
	else:
		print('#'*50)

	return render(request, 'contacts.html')


def blog(request):
	posts = Post.objects.all()
	print(type(posts))
	return render(request, 'blog.html', {'posts':posts})

def blog_detail(request,post_slug):
	post = Post.objects.get(slug=post_slug)
	if request.method == 'POST':
		name = request.POST['name']
		email = request.POST['email']
		subject = request.POST['subject']
		message = request.POST['message']
	
		comment = Comment.objects.create(
				name=name,
				email=email,
				subject=subject,
				message=message
				)
		comment.post = post
		comment.save()
	

		messages.add_message(request, messages.SUCCESS, 'Muhokama qabul qilindi !')
	else:
		messages.add_message(request, messages.WARNING, 'Muhokama qabul qilinmadi !!!')


	context = {
		'post':post,
	}
		
	return render(request, 'post.html',context)	

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Shelly School HTML Template</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Shelly - Website" />
	<meta name="author" content="merkulove">
	<meta name="keywords" content="" />
	<link rel="icon" href="assets/img/favicon.png">
	<link rel="stylesheet" type="text/css" href="assets/css/animate.css">
	<link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="assets/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="assets/css/main.css">
	<link rel="stylesheet" type="text/css" href="assets/css/responsive.css">
</head>


<body>

	<div class="wrapper">

		<div class="error-page">
			<h2 class="page-title">Shelly</h2>
			<div class="container">
				<div class="error-text">
					<h2>Oops!</h2>
					<h3>The page does not exist</h3>
					<a href="index.html" title="" class="btn-default">Home Page <i class="fa fa-long-arrow-alt-right"></i></a>
					<ul class="social-icons">
						<li><a href="#" title=""><i class="fab fa-facebook-f"></i></a></li>
						<li><a href="#" title=""><i class="fab fa-twitter"></i></a></li>
						<li><a href="#" title=""><i class="fab fa-linkedin-in"></i></a></li>
					</ul><!--social-icons end-->
				</div><!--error-text end-->
			</div>
		</div><!--error-page end-->

	</div><!--wrapper end-->


<script src="assets/js/jquery.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/isotope.js"></script>
<script src="assets/js/html5lightbox.js"></script>
<script src="assets/js/slick.min.js"></script>
<script src="assets/js/tweenMax.js"></script>
<script src="assets/js/scripts.js"></script>

</body>

</html>

templates/post.html
{% extends 'wrapper.html' %}
{% load static %}
{% block  content %}

		<section class="pager-section blog-version" 
		style="background-image:url({{post.image.url}});">
			<div class="container">
				<div class="pager-content text-center">
					<ul>
						<li><a href="#" title="">Home</a></li>
						<li><a href="#" title="">Blog</a></li>
						<li><span>{{post.title}}</span></li>
						
					</ul>
					<h2>{{post.title}}</h2>
					<span class="categry">{{post.category}}</span>
					<ul class="meta">
						<li><a href="#" title="">{{post.published}}</a></li>
						<li><a href="#" title="">{{post.author}}</a></li>
						<li><img src="/static/assets/img/icon13.png" alt="" /><a href="#" title="">{{post.tag}}</a></li>
					</ul>
				</div><!--pager-content end-->
			</div>
		</section><!--pager-section end-->

		<section class="page-content p80">
			<div class="container">
				<div class="row">
					<div class="col-lg-9">
						<div class="blog-post single">
							<center>
<div class="text-center">
	{% if messages %}
	<ul class="messages">
	    {% for message in messages %}
	    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	    {% endfor %}
	</ul>
	{% endif %}
</div>
</center>

							<p>{{post.body|safe}}</p>
							
						</div><!--blog-post single end-->
						<div class="mdp-post-comments">
							<h3 class="mdp-sub-title">Muhokamalar {{post.comment_set.all.count}}</h3>
							<ul>
								{% for c in post.comment_set.all|slice:'10' %}
								<li>
									<div class="mdp-comment d-flex flex-wrap">
										<div class="mdp-img">
											<img src="https://via.placeholder.com/72x72" alt="">
										</div>
										<div class="mdp-com">
											<h3>{{c.name}}</h3>
											<span>25/09/2020</span>
											<p>{{c.message}}</p>
											<a href="#" title="" class="reply-btn"><i class="fa fa-reply"></i>Reply</a>
										</div>
									</div><!--mdp-comment end-->
								</li>
							{% endfor %}
							</ul>
						</div><!--post-comments end-->
						<div class="mdp-contact">
							<div class="comment-area">
								<h3 class="mdp-sub-title">Fikr bildirish</h3>
								<form action="" method="POST">
									<div class="row">
										<div class="col-lg-4">
											<div class="form-group">
												<input type="text" name="name" placeholder="Ism">
											</div><!--form-group end-->
										</div>
										{% csrf_token %}
										<div class="col-lg-4">
											<div class="form-group">
												<input type="email" name="email" placeholder="Email">
											</div><!--form-group end-->
										</div>
										<div class="col-lg-4">
											<div class="form-group">
												<input type="text" name="subject" placeholder="Mavzu">
											</div><!--form-group end-->
										</div>
										<div class="col-lg-12">
											<div class="form-group">
												<textarea name="message" placeholder="Xabar matni .."></textarea>
											</div><!--form-group end-->
										</div>
										<div class="col-lg-12">
											<div class="form-submit">
												<button type="submit"  class="btn-default">Yuborish <i class="fa fa-long-arrow-alt-right"></i></button>
											</div><!--form-submit end-->
										</div>
									</div>
								</form>
							</div><!--comment-area end-->
						</div><!--mdp-contact end-->
					</div>
					<div class="col-lg-3">
						<div class="sidebar">
							<div class="widget widget-search">
								<form>
									<input type="text" name="search" placeholder="Search">
									<button type="submit"><img src="assets/img/icon4.png" alt=""></button>
								</form>
							</div><!--widget-search end-->
							<div class="widget widget-categories">
								<h3 class="widget-title">Categories</h3>
								<ul>
									<li>
										<a href="#" title="">Teachers</a>
										<span>45</span>
									</li>
									<li>
										<a href="#" title="">School News</a>
										<span>13</span>
									</li>
									<li>
										<a href="#" title="">Lessons</a>
										<span>6</span>
									</li>
									<li>
										<a href="#" title="">Shelly</a>
										<span>89</span>
									</li>
								</ul>
							</div><!--widget-categories end-->
							<div class="widget widget-posts">
								<h3 class="widget-title">Latest Posts</h3>
								<div class="wd-posts">
									<div class="wd-post d-flex flex-wrap">
										<div class="wd-thumb">
											<img src="https://via.placeholder.com/52x52" alt="">
										</div>
										<div class="wd-info">
											<h3><a href="#" title="">Duis tempor eros tortor, a ornare</a></h3>
											<span>17/09/2020</span>
										</div>
									</div><!--wd-post end-->
									<div class="wd-post d-flex flex-wrap">
										<div class="wd-thumb">
											<img src="https://via.placeholder.com/52x52" alt="">
										</div>
										<div class="wd-info">
											<h3><a href="#" title="">Duis tempor eros tortor, a ornare</a></h3>
											<span>17/09/2020</span>
										</div>
									</div><!--wd-post end-->
									<div class="wd-post d-flex flex-wrap">
										<div class="wd-thumb">
											<img src="https://via.placeholder.com/52x52" alt="">
										</div>
										<div class="wd-info">
											<h3><a href="#" title="">Duis tempor eros tortor, a ornare</a></h3>
											<span>17/09/2020</span>
										</div>
									</div><!--wd-post end-->
								</div><!--wd-posts end-->
							</div><!--widget-posts end-->
			
							<div class="widget widget-tags">
								<h3 class="widget-title">Tags</h3>
								<ul>
									<li>
										<a href="#" title="">Teachers</a>
									</li>
									<li>
										<a href="#" title="">Lessons</a>
									</li>
									<li>
										<a href="#" title="">Shelly</a>
									</li>
									<li>
										<a href="#" title="">School</a>
									</li>
									<li>
										<a href="#" title="">Theme</a>
									</li>
									<li>
										<a href="#" title="">Class</a>
									</li>
								</ul>
							</div><!--widget-tags end-->
						
						</div><!--sidebar end-->
					</div>
				</div>
			</div>
		</section>

		<section class="newsletter-section">
			<div class="container">
				<div class="newsletter-sec">
					<div class="row align-items-center">
						<div class="col-lg-4">
							<div class="newsz-ltr-text">
								<h2>Join us <br /> and stay tuned!</h2>
								<a href="contacts.html" title="" class="btn-default">Join Us <i class="fa fa-long-arrow-alt-right"></i></a>
							</div><!--newsz-ltr-text end-->
						</div>
						<div class="col-lg-8">
							<form class="newsletter-form">
								<div class="row">
									<div class="col-md-4">
										<div class="form-group">
											<input type="text" name="name" placeholder="Name">
										</div><!--form-group end-->
									</div>
									<div class="col-md-4">
										<div class="form-group">
											<input type="email" name="email" placeholder="Email">
										</div><!--form-group end-->
									</div>
									<div class="col-md-4">
										<div class="form-group select-tg">
											<select>
												<option>Class</option>
												<option>Class</option>
												<option>Class</option>
												<option>Class</option>
												<option>Class</option>
												<option>Class</option>
											</select>
										</div><!--form-group end-->
									</div>
									<div class="col-md-12">
										<div class="form-group">
											<textarea name="message" placeholder="Message"></textarea>
										</div><!--form-group end-->
									</div>
								</div>
							</form><!--newsletter-form end-->
						</div>
					</div>
				</div><!--newsletter-sec end-->
			</div>
		</section><!--newsletter-sec end-->
{% endblock %}

templates/wrapper.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Nature Code </title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Shelly - Website" />
	<meta name="author" content="merkulove">
	<meta name="keywords" content="" />
	<link rel="icon" href="assets/img/favicon.png">
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/responsive.css' %}">
</head>


<body>

	<div class="wrapper">
		
		<div class="main-section">

			<header>
				<div class="container">
					<div class="header-content d-flex flex-wrap align-items-center">
						<div class="logo">
							<a href="#" title="">
								<img src="/static/assets/img/logo.png" alt="" srcset="/static/assets/img/01_Logo_2x.png 2x"> 
							</a>
						</div><!--logo end-->
						<ul class="contact-add d-flex flex-wrap">
							<li>
								<div class="contact-info">
									<img src="/static/assets/img/icon1.png" alt="">
									<div class="contact-tt">
										<h4>Telefon</h4>
										<span>+998 99 123 45 67 </span>
									</div>
								</div><!--contact-info end-->
							</li>
							<li>
								<div class="contact-info">
									<img src="/static/assets/img/icon2.png" alt="">
									<div class="contact-tt">
										<h4>Ish vaqti</h4>
										<span>Du - Shan 08:00 - 19:00</span>
									</div>
								</div><!--contact-info end-->
							</li>
							<li>
								<div class="contact-info">
									<img src="/static/assets/img/icon3.png" alt="">
									<div class="contact-tt">
										<h4>Manzil</h4>
										<span>Andijon sh. Yangibozor</span>
									</div>
								</div><!--contact-info end-->
							</li>
						</ul><!--contact-information end-->
						<div class="menu-btn">
							<a href="#">
								<span class="bar1"></span>
								<span class="bar2"></span>
								<span class="bar3"></span>
							</a>
						</div><!--menu-btn end-->
					</div><!--header-content end-->
					<div class="navigation-bar d-flex flex-wrap align-items-center">
						<nav>
							<ul>
								<li><a class="active" href="{% url 'main:homePage' %}" title="">Bosh sahifa</a></li>
								<li><a href="about.html" title="">Biz haqimizda</a>
									<ul>
										<li><a href="events.html" title="">Events</a>
											<ul>
												<li><a href="event-single.html" title="">Event Single</a></li>
											</ul>
										</li>
										<li><a href="schedule.html" title="">Schedule</a></li>
										<li><a href="error.html" title="">404</a></li>
									</ul>
								</li>
								<li><a href="classes.html" title="">Kurslar</a>
									<ul>
										<li><a href="class-single.html" title="">Class Single</a></li>
									</ul>
								</li>
								<li><a href="teachers.html" title="">Ustozlar</a>
									<ul>
										<li><a href="teacher-single.html" title="">Teacher Single</a></li>
									</ul>
								</li>
								<li><a href="{% url 'main:blogPage' %}" title="">Blog</a>
					
								</li>
								<li><a href="{% url 'main:contactPage' %}" title="">Aloqa</a></li>
							</ul>
						</nav><!--nav end-->
						<ul class="social-links ml-auto">
							<li><a href="#" title=""><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" title=""><i class="fab fa-linkedin-in"></i></a></li>
							<li><a href="#" title=""><i class="fab fa-instagram"></i></a></li>
						</ul>
					</div><!--navigation-bar end-->
				</div>
			</header><!--header end-->

			<div class="responsive-menu">
				<ul>
					<li><a href="index.html" title="">Home</a></li>
					<li><a href="about.html" title="">About</a></li>
					<li><a href="events.html" title="">Events</a></li>
					<li><a href="event-single.html" title="">Event Single</a></li>
					<li><a href="schedule.html" title="">Schedule</a></li>
					<li><a href="classes.html" title="">Classes</a></li>
					<li><a href="class-single.html" title="">Classe Single</a></li>
					<li><a href="teachers.html" title="">Teachers</a></li>
					<li><a href="teacher-single.html" title="">Teacher Single</a></li>
					<li><a href="blog.html" title="">Blog</a></li>
					<li><a href="post.html" title="">Blog Single</a></li>
					<li><a href="contacts.html" title="">Contacts</a></li>
					<li><a href="error.html" title="">404</a></li>
				</ul>
			</div><!--responsive-menu end-->

{% block content %}

{% endblock %}

	<footer>
			<div class="container">
				<div class="top-footer">
					<div class="row">
						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="widget widget-about">
								<img src="assets/img/logo.png" alt="">
								<p>Vivamus porta efficitur nibh nec convallis. Vestibulum egestas eleifend justo. Ut tellus ipsum, accumsan</p>
							</div><!--widget-about end-->
						</div>
						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="widget widget-contact">
								<ul class="contact-add">
									<li>
										<div class="contact-info">
											<img src="assets/img/icon1.png" alt="">
											<div class="contact-tt">
												<h4>Call</h4>
												<span>+2 342 5446 67</span>
											</div>
										</div><!--contact-info end-->
									</li>
									<li>
										<div class="contact-info">
											<img src="assets/img/icon2.png" alt="">
											<div class="contact-tt">
												<h4>Work Time</h4>
												<span>Mon - Fri 8 AM - 5 PM</span>
											</div>
										</div><!--contact-info end-->
									</li>
									<li>
										<div class="contact-info">
											<img src="assets/img/icon3.png" alt="">
											<div class="contact-tt">
												<h4>Address</h4>
												<span>Franklin St, Greenpoint Ave</span>
											</div>
										</div><!--contact-info end-->
									</li>
								</ul>
							</div><!--widget-contact end-->
						</div>
						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="widget widget-links">
								<h3 class="widget-title">Quick Links</h3>
								<ul>
									<li><a href="about.html" title="">About Us </a></li>
									<li><a href="classes.html" title="">Our Classes</a></li>
									<li><a href="teachers.html" title="">School Teachers </a></li>
									<li><a href="events.html" title="">Recent Events </a></li>
									<li><a href="blog.html" title="">Our News </a></li>
									<li><a href="schedule.html" title="">Schedule </a></li>
								</ul>
							</div><!--widget-links end-->
						</div>
						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="widget widget-iframe">
								<iframe src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=1%20Grafton%20Street,%20Dublin,%20Ireland+(My%20Business%20Name)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe>
							</div><!--widget-iframe end-->
						</div>
					</div>
				</div><!--top-footer end-->
				<div class="bottom-footer">
					<div class="row align-items-center">
						<div class="col-lg-6 col-md-6 col-sm-6">
							<p>© Copyrights 2020 Shelly All rights reserved</p>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<ul class="social-links">
								<li><a href="#" title=""><i class="fab fa-facebook-f"></i></a></li>
								<li><a href="#" title=""><i class="fab fa-linkedin-in"></i></a></li>
								<li><a href="#" title=""><i class="fab fa-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</div><!--bottom-footer end-->
			</div>
		</footer><!--footer end-->

	</div>



<script src="{% static 'assets/js/jquery.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/isotope.js' %}"></script>
<script src="{% static 'assets/js/html5lightbox.js' %}"></script>
<script src="{% static 'assets/js/slick.min.js' %}"></script>
<script src="{% static 'assets/js/tweenMax.js' %}"></script>
<script src="{% static 'assets/js/scripts.js' %}"></script>


</body>

</html>